apiVersion: v2
name: sematic-server
description: Sematic AI Server
type: application
version: 1.0.5
appVersion: v0.24.0
maintainers:
  - name: sematic-ai
    url: https://github.com/sematic-ai/sematic/
