apiVersion: v2
name: sematic-server
description: Sematic AI Server
type: application
version: 1.0.2
appVersion: v0.22.1
maintainers:
  - name: sematic-ai
    url: https://github.com/sematic-ai/sematic/
